apiVersion: v2
name: knawd-deployer
description: A helm chart to deploy a WASI enabled crun.

keywords:
  - wasi
  - wasm
  - crun
sources:
  - https://github.com/uirlis/wasi-core-deployer

type: application

version: v1.1.0

appVersion: "v1.1.0"

icon: https://raw.githubusercontent.com/knawd/documentation/main/icons/cookie-6116766.svg

maintainers:
  - name: No9
    email: anton@venshare.com
    url: https://github.com/No9/

annotations:
  artifacthub.io/changes: |
    - kind: added
      description:  Support for microk8s
      links:
        - name: GitHub PR
          url: https://github.com/knawd/deployer/pull/12
  artifacthub.io/images: |
    - name: knawd-deployer
      image: quay.io/knawd/deployer:v1.1.0
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: BED079E67FD431E45301B1C9949E671B46AC8A34
    url: https://keybase.io/antonwhalley/pgp_keys.asc
